apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: angular-webapp
  name: angular-webapp
spec:
  replicas: 5
  selector: 
    matchLab  els:
      app: angular-webapp
  strategy: {}
  template:
    metadata: 
      creationTimestamp: null
      labe  ls:
        app: angular-webapp
    spec: 
      containers:
      - image: docker.io/bbachin1/angular-node-webapp
        name: webapp
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 3080 

status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: angular-webapp
  labels:
    run: ang  ular-webapp
spec: 
  ports:
  - port: 3080
    pr  otocol: TCP
  selector:
    app: angular-webapp
  type: LoadBalancer

